# Generated by Django 5.1.6 on 2025-02-10 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theater", "0003_alter_reservation_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actor",
            name="first_name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="actor",
            name="last_name",
            field=models.CharField(max_length=50),
        ),
    ]
